--Andrew Knapp
--MSIS 527 L711
--Database Management 1
--Assignment 4

--Question 1
SELECT CUSTFIRSTNAME, CUSTLASTNAME FROM CUSTOMER

--Quesiton 2
SELECT CUSTNO FROM CUSTOMER WHERE CUSTBAL = (SELECT MAX(CUSTBAL) FROM CUSTOMER)

--Question 3
SELECT CUSTNO FROM CUSTOMER WHERE CUSTBAL = (SELECT MIN(CUSTBAL) FROM CUSTOMER)

--Question 4
SELECT COUNT(*) FROM ORDERTBL WHERE (SELECT EMPLOYEE.EMPNO FROM EMPLOYEE WHERE EMPFIRSTNAME = 'Landi' AND EMPLASTNAME = 'Santos') = ORDERTBL.EMPNO

--Question 5
SELECT ORDNO FROM ORDERTBL WHERE (SELECT EMPLOYEE.EMPNO FROM EMPLOYEE WHERE EMPFIRSTNAME = 'Landi' AND EMPLASTNAME = 'Santos') = ORDERTBL.EMPNO

--Question 6
SELECT DISTINCT CUSTFIRSTNAME AS CustomerFirstName, CUSTLASTNAME AS CustomerLastName, EMPFIRSTNAME AS EmployeeFirstName, EMPLASTNAME AS EmployeeLastName FROM (EMPLOYEE INNER JOIN ORDERTBL ON EMPLOYEE.EMPNO = ORDERTBL.EMPNO)INNER JOIN CUSTOMER ON CUSTOMER.CUSTNO = ORDERTBL.CUSTNO

--Question 7
SELECT ORDNO FROM ORDERTBL WHERE EMPNO IS NULL

--Question 8
SELECT CUSTFIRSTNAME AS CustomerFirstName, CUSTLASTNAME AS CustomerLastName, COUNT(*) AS NumberOfOrders FROM CUSTOMER, ORDERTBL WHERE CUSTOMER.CUSTNO = ORDERTBL.CUSTNO GROUP BY CUSTFIRSTNAME, CUSTLASTNAME 

--Question 9
SELECT EMPNO, EMPEMAIL FROM EMPLOYEE MINUS (SELECT DISTINCT EMPLOYEE.EMPNO, EMPLOYEE.EMPEMAIL FROM EMPLOYEE, ORDERTBL WHERE EMPLOYEE.EMPNO = ORDERTBL.EMPNO)

--Question 10
SELECT ORDDATE, COUNT(*) OrderCount FROM ORDERTBL GROUP BY ORDDATE ORDER BY OrderCount DESC