--Andrew Knapp
--MSIS 527 L711
--Database Management 1
--Assignment 9

--Question 1 Answer:
CREATE VIEW S3399214Products AS
SELECT * FROM PRODUCT
WHERE SuppNo = 'S3399214';

--Question 2 Answer:
CREATE VIEW JANUARY2013ORDERINFO AS
SELECT ORDERTBL.ORDNO,ORDDATE,CUSTNO,EMPNO,ORDNAME,ORDSTREET,ORDCITY,ORDSTATE,ORDZIP,QTY,PRODNAME FROM ORDERTBL,ORDLINE,PRODUCT
WHERE ORDERTBL.OrdNo = ORDLINE.OrdNo
AND ORDLINE.ProdNo = Product.ProdNo
AND to_number(to_char(ORDDATE,'MM'))=1 
AND to_number(to_char(ORDDATE,'YYYY'))=2013;

--Question 3 Answer:
CREATE VIEW NUMBEROFPRODUCTORDERS AS
SELECT PRODUCT.ProdNo,ProdName,ProdPrice,ProdQOH,COUNT(ORDLINE.ProdNo) AS NumberOfOrders 
FROM PRODUCT LEFT JOIN ORDLINE
ON PRODUCT.ProdNo = ORDLINE.ProdNo
GROUP BY PRODUCT.ProdNo, ProdName, ProdPrice, ProdQOH;

--Question 4 Answer:
SELECT * FROM S3399214Products
WHERE PRODPRICE > 300;

--Question 5 Answer:
SELECT * FROM JANUARY2013ORDERINFO
WHERE PRODNAME LIKE '%Ink Jet%';
